language: python
sudo: false
env:
  global:
    - DEPS=$HOME/deps
    - PATH=$DEPS/bin:$PATH
before_script: |
  git clone https://github.com/junegunn/vader.vim.git
  git clone https://github.com/tpope/vim-repeat
script: test/run !
